export const tableData = {
    count: 4304,
    items: [
        {
            id: 1153144,
            villageName: '融创揽月府',
            villageId: 150879,
            name: '融创揽月府',
            developer: '陕西凯瑞房地产开发有限公司',
            city: '西安市',
            district: '长安区',
            newhouseType: '代理商',
            source: null,
            sourceValue: 8,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-22 19:04',
            firstLiveTime: null,
            sellStatus: '待售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['别墅'],
        },
        {
            id: 1153143,
            villageName: '赞成太和广场',
            villageId: 5596,
            name: '赞成太和广场',
            developer: null,
            city: '杭州市',
            district: '上城区',
            newhouseType: '代理商',
            source: '北京华夏保险经纪有限公司',
            sourceValue: 8,
            creatorName: '许悦',
            phone: '18852223222',
            updateTime: '2019-08-22 18:09',
            firstLiveTime: null,
            sellStatus: null,
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅', '公寓'],
        },
        {
            id: 1153142,
            villageName: '天地源·大都会',
            villageId: 150878,
            name: '天地源·大都会',
            developer: '西安天地源曲江房地产开发有限公司',
            city: '西安市',
            district: null,
            newhouseType: '代理商',
            source: null,
            sourceValue: 8,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-22 15:02',
            firstLiveTime: null,
            sellStatus: '待售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1151942,
            villageName: '融创瑷颐湾',
            villageId: 149649,
            name: '融创瑷颐湾',
            developer: '浙江融科智地房地产开发有限公司',
            city: '杭州市',
            district: '余杭区',
            newhouseType: '代理商',
            source: null,
            sourceValue: 8,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-22 14:21',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153141,
            villageName: '万科·大都会',
            villageId: 150877,
            name: '万科·大都会',
            developer: '西咸新区昊鼎置业有限公司',
            city: '西安市',
            district: null,
            newhouseType: '全网',
            source: '房天下',
            sourceValue: 11,
            creatorName: null,
            phone: '4008988468',
            updateTime: '2019-08-22 12:01',
            firstLiveTime: null,
            sellStatus: '在售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153140,
            villageName: 'Central King上寓',
            villageId: 150876,
            name: 'Central King上寓',
            developer: '莱安集团',
            city: '西安市',
            district: null,
            newhouseType: '全网',
            source: '房天下',
            sourceValue: 11,
            creatorName: null,
            phone: '400-890-0000 转 898397',
            updateTime: '2019-08-22 11:05',
            firstLiveTime: null,
            sellStatus: '在售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153139,
            villageName: '融创望海潮',
            villageId: 7376,
            name: '融创望海潮',
            developer: '杭州嘉科置业有限公司',
            city: '杭州市',
            district: '萧山区',
            newhouseType: '合作',
            source: null,
            sourceValue: 2,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-21 17:12',
            firstLiveTime: '2017-08-03',
            sellStatus: '在售',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153138,
            villageName: '世贸中心',
            villageId: 1706,
            name: '世贸中心lulu',
            developer: '测试开发商',
            city: '杭州市',
            district: '',
            newhouseType: '合作',
            source: '陆闻霜的代理公司2',
            sourceValue: 2,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-20 14:35',
            firstLiveTime: '2019-08-21',
            sellStatus: null,
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: null,
        },
        {
            id: 1153137,
            villageName: '陆家坞',
            villageId: 5905,
            name: '陆家坞',
            developer: '陆测试企业',
            city: '杭州市',
            district: '',
            newhouseType: '合作',
            source: '陆闻霜的代理公司2',
            sourceValue: 2,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-20 11:39',
            firstLiveTime: null,
            sellStatus: null,
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: null,
        },
        {
            id: 1153136,
            villageName: '21',
            villageId: 28,
            name: '2122',
            developer: '万科地产',
            city: '临沂市',
            district: '兰山区',
            newhouseType: '合作',
            source: null,
            sourceValue: 2,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-16 15:59',
            firstLiveTime: null,
            sellStatus: '在售',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅', '公寓'],
        },
        {
            id: 1153135,
            villageName: '21',
            villageId: 28,
            name: 'chl测试1',
            developer: '万科地产',
            city: '临沂市',
            district: '',
            newhouseType: '代理商',
            source: null,
            sourceValue: 8,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-15 14:52',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153134,
            villageName: '21',
            villageId: 28,
            name: '21',
            developer: '万科地产',
            city: '临沂市',
            district: '',
            newhouseType: '合作',
            source: null,
            sourceValue: 2,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-14 20:16',
            firstLiveTime: null,
            sellStatus: '待售',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['公寓'],
        },
        {
            id: 1153133,
            villageName: '21',
            villageId: 28,
            name: '21',
            developer: '万科地产',
            city: '临沂市',
            district: '',
            newhouseType: '代理商',
            source: null,
            sourceValue: 8,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-14 20:06',
            firstLiveTime: null,
            sellStatus: '在售',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1152695,
            villageName: '和达滨江花园',
            villageId: 150578,
            name: '和达滨江花园',
            developer: '湖南和达投资集团有限公司',
            city: '湘潭市',
            district: '岳塘区',
            newhouseType: '合作',
            source: '公司前端测试12343512',
            sourceValue: 2,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-14 09:48',
            firstLiveTime: null,
            sellStatus: '待售',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153132,
            villageName: '白塔人家',
            villageId: 4332,
            name: '白塔人家-新房详情测试',
            developer: null,
            city: '杭州市',
            district: '上城区',
            newhouseType: '代理商',
            source: '浙商银行股份有限公司',
            sourceValue: 8,
            creatorName: '陈冠鸿',
            phone: '18668062260',
            updateTime: '2019-08-13 16:58',
            firstLiveTime: '2019-06-28',
            sellStatus: null,
            onlineStatus: 3,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153131,
            villageName: '陈冠鸿测试',
            villageId: 150873,
            name: '陈冠鸿测试',
            developer: null,
            city: '杭州市',
            district: '下城区',
            newhouseType: '代理商',
            source: '浙商银行股份有限公司',
            sourceValue: 8,
            creatorName: '陈冠鸿',
            phone: '18668062260',
            updateTime: '2019-08-13 16:51',
            firstLiveTime: null,
            sellStatus: null,
            onlineStatus: 3,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153130,
            villageName: '中大银泰城',
            villageId: 615,
            name: '中大银泰城',
            developer: '杭州理想银泰购物中心有限公司',
            city: '杭州市',
            district: '下城区',
            newhouseType: '代理商',
            source: '承道房产',
            sourceValue: 8,
            creatorName: '谢凯峰',
            phone: '17681809215',
            updateTime: '2019-08-13 16:47',
            firstLiveTime: '2019-08-20',
            sellStatus: '在售',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅', '公寓'],
        },
        {
            id: 1151406,
            villageName: '中旅名门府新境',
            villageId: 150156,
            name: '中旅名门府新境',
            developer: '杭州港中旅城市发展有限公司',
            city: '杭州市',
            district: '萧山区',
            newhouseType: '代理商',
            source: '承道房产',
            sourceValue: 8,
            creatorName: '谢凯峰',
            phone: '17681809215',
            updateTime: '2019-08-13 16:34',
            firstLiveTime: '2019-05-11',
            sellStatus: '在售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153129,
            villageName: '融创望海潮',
            villageId: 7376,
            name: '融创望海潮',
            developer: '杭州嘉科置业有限公司',
            city: '杭州市',
            district: '萧山区',
            newhouseType: '代理商',
            source: '承道房产',
            sourceValue: 8,
            creatorName: '谢凯峰',
            phone: '17681809215',
            updateTime: '2019-08-13 16:32',
            firstLiveTime: '2017-08-03',
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1152173,
            villageName: '融创望海潮',
            villageId: 7376,
            name: '融创望海潮',
            developer: '杭州嘉科置业有限公司',
            city: '杭州市',
            district: '萧山区',
            newhouseType: '代理商',
            source: null,
            sourceValue: 8,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-13 15:55',
            firstLiveTime: '2017-08-03',
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153128,
            villageName: '春江花月映霞苑',
            villageId: 4149,
            name: '春江花月映霞苑',
            developer: '绿城置业有限公司',
            city: '杭州市',
            district: '',
            newhouseType: '代理商',
            source: '承道房产',
            sourceValue: 8,
            creatorName: '谢凯峰',
            phone: '17681809215',
            updateTime: '2019-08-13 15:00',
            firstLiveTime: null,
            sellStatus: '待售',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1152716,
            villageName: '万事利大厦',
            villageId: 750,
            name: '万事利大厦',
            developer: '杭州绿城致青春网络科技有限公司',
            city: '杭州市',
            district: '',
            newhouseType: '合作',
            source: '公司前端测试12343512',
            sourceValue: 2,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-13 13:39',
            firstLiveTime: null,
            sellStatus: null,
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: null,
        },
        {
            id: 1151413,
            villageName: '碧桂园越溪府',
            villageId: 149320,
            name: '碧桂园越溪府',
            developer: '杭州碧泰置业有限公司, 杭州碧桂园房地产开发有限公司',
            city: '杭州市',
            district: '萧山区',
            newhouseType: '合作',
            source: '公司前端测试12343512',
            sourceValue: 2,
            creatorName: '管理员',
            phone: '13521023559',
            updateTime: '2019-08-09 14:33',
            firstLiveTime: '2017-10-12',
            sellStatus: null,
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: null,
        },
        {
            id: 1153127,
            villageName: '曦园',
            villageId: 150866,
            name: '曦园',
            developer: '云南澎柏投资有限公司',
            city: '昆明市',
            district: '五华区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608814,0338',
            updateTime: '2019-08-08 11:47',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153126,
            villageName: '人民路壹号广场',
            villageId: 150872,
            name: '人民路壹号广场',
            developer: '云南昆都国际房地产开发有限公司',
            city: '昆明市',
            district: '五华区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608791,0415',
            updateTime: '2019-08-08 11:47',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153125,
            villageName: '海伦先生',
            villageId: 150871,
            name: '海伦先生',
            developer: '云南天福房地产开发有限公司',
            city: '昆明市',
            district: '五华区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608386,8636',
            updateTime: '2019-08-08 11:47',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153124,
            villageName: '怡合景苑',
            villageId: 150870,
            name: '怡合景苑',
            developer: '昆明城欣置业有限公司',
            city: '昆明市',
            district: '五华区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608386,7377',
            updateTime: '2019-08-08 11:47',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153123,
            villageName: '昆明新城吾悦广场',
            villageId: 150869,
            name: '昆明新城吾悦广场',
            developer: '昆明新城吾悦房地产发展有限公司',
            city: '昆明市',
            district: '五华区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608750,7729',
            updateTime: '2019-08-08 11:47',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153122,
            villageName: '银河明珠',
            villageId: 150868,
            name: '银河明珠',
            developer: '云南江东房地产集团有限公司',
            city: '昆明市',
            district: '五华区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608813,0467',
            updateTime: '2019-08-08 11:47',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153121,
            villageName: '碧桂园半山龙庭',
            villageId: 150867,
            name: '碧桂园半山龙庭',
            developer: '昆明碧泰房地产开发有限公司',
            city: '昆明市',
            district: '五华区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608397,6232',
            updateTime: '2019-08-08 11:47',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153120,
            villageName: '曦园',
            villageId: 150866,
            name: '曦园',
            developer: '云南澎柏投资有限公司',
            city: '昆明市',
            district: '五华区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608813,7468',
            updateTime: '2019-08-08 11:47',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['别墅'],
        },
        {
            id: 1153119,
            villageName: '融创春风十里',
            villageId: 150865,
            name: '融创春风十里',
            developer: '云南融科科技产业投资有限公司',
            city: '昆明市',
            district: '五华区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608399,5866',
            updateTime: '2019-08-08 11:47',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153118,
            villageName: '莲花池畔',
            villageId: 150864,
            name: '莲花池畔',
            developer: '云南金鼎盛房地产开发有限公司',
            city: '昆明市',
            district: '五华区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608372,7082',
            updateTime: '2019-08-08 11:47',
            firstLiveTime: null,
            sellStatus: '在售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['公寓'],
        },
        {
            id: 1153117,
            villageName: '固地尚诚商务中心',
            villageId: 150863,
            name: '固地尚诚商务中心',
            developer: '昆明固地凡哥房地产开发有限公司',
            city: '昆明市',
            district: '五华区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608371,6886',
            updateTime: '2019-08-08 11:47',
            firstLiveTime: null,
            sellStatus: '在售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['公寓'],
        },
        {
            id: 1153116,
            villageName: '凯旋城',
            villageId: 150862,
            name: '凯旋城',
            developer: '云南佳泽投资有限公司',
            city: '昆明市',
            district: '石林彝族自治县',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608895,3516',
            updateTime: '2019-08-08 11:46',
            firstLiveTime: null,
            sellStatus: '待售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['商铺'],
        },
        {
            id: 1153115,
            villageName: '凯旋城',
            villageId: 150862,
            name: '凯旋城',
            developer: '云南佳泽投资有限公司',
            city: '昆明市',
            district: '石林彝族自治县',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608909,4047',
            updateTime: '2019-08-08 11:46',
            firstLiveTime: null,
            sellStatus: '在售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153112,
            villageName: '世纪阳光',
            villageId: 150598,
            name: '世纪阳光',
            developer: '石林广建房地产开发有限公司',
            city: '昆明市',
            district: '石林彝族自治县',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608759,9161',
            updateTime: '2019-08-08 11:46',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153114,
            villageName: '颐林尚都',
            villageId: 150861,
            name: '颐林尚都',
            developer: '云南鹏森房地产开发有限公司',
            city: '昆明市',
            district: '石林彝族自治县',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608279,7959',
            updateTime: '2019-08-08 11:46',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153113,
            villageName: '世纪阳光',
            villageId: 150598,
            name: '世纪阳光',
            developer: '石林广建房地产开发有限公司',
            city: '昆明市',
            district: '石林彝族自治县',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608890,0429',
            updateTime: '2019-08-08 11:46',
            firstLiveTime: null,
            sellStatus: '在售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['公寓'],
        },
        {
            id: 1153111,
            villageName: '凯旋怡景',
            villageId: 150860,
            name: '凯旋怡景',
            developer: '云南佳泽投资有限公司',
            city: '昆明市',
            district: '石林彝族自治县',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608343,2816',
            updateTime: '2019-08-08 11:46',
            firstLiveTime: null,
            sellStatus: '在售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153110,
            villageName: '世纪阳光',
            villageId: 150598,
            name: '世纪阳光',
            developer: '石林广建房地产开发有限公司',
            city: '昆明市',
            district: '石林彝族自治县',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608876,8319',
            updateTime: '2019-08-08 11:46',
            firstLiveTime: null,
            sellStatus: '待售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['商铺'],
        },
        {
            id: 1153109,
            villageName: '招商海公馆',
            villageId: 150622,
            name: '招商海公馆',
            developer: '云南招商城投房地产有限公司',
            city: '昆明市',
            district: '官渡区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608301,8336',
            updateTime: '2019-08-08 11:46',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153108,
            villageName: '德润朗悦湾',
            villageId: 150778,
            name: '德润朗悦湾',
            developer: '云南德润城市投资发展有限公司',
            city: '昆明市',
            district: '盘龙区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608755,6966',
            updateTime: '2019-08-08 11:45',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['商铺'],
        },
        {
            id: 1152982,
            villageName: '云通嘉园',
            villageId: 150775,
            name: '云通嘉园',
            developer: '云南云通房地产开发经营有限公司',
            city: '昆明市',
            district: '盘龙区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608295,5514',
            updateTime: '2019-08-08 11:45',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153107,
            villageName: '碧桂园北城映象',
            villageId: 150770,
            name: '碧桂园北城映象',
            developer: '云南碧宁房地产开发有限公司',
            city: '昆明市',
            district: '盘龙区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608752,3812',
            updateTime: '2019-08-08 11:45',
            firstLiveTime: null,
            sellStatus: '待售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['商铺'],
        },
        {
            id: 1153014,
            villageName: '瑞鼎城',
            villageId: 150717,
            name: '瑞鼎城',
            developer: '昆明尊良房地产开发有限公司',
            city: '昆明市',
            district: '盘龙区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608754,8717',
            updateTime: '2019-08-08 11:45',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
        {
            id: 1153106,
            villageName: '爱尚苑',
            villageId: 150859,
            name: '爱尚苑',
            developer: '云南世邦房地产开发有限公司',
            city: '昆明市',
            district: '盘龙区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608746,4871',
            updateTime: '2019-08-08 11:45',
            firstLiveTime: null,
            sellStatus: '待售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['商铺'],
        },
        {
            id: 1153105,
            villageName: '俊发逸天峰',
            villageId: 150781,
            name: '俊发逸天峰',
            developer: '云南俊发房地产有限责任公司',
            city: '昆明市',
            district: '盘龙区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608407,5571',
            updateTime: '2019-08-08 11:45',
            firstLiveTime: null,
            sellStatus: '待售',
            onlineStatus: 1,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['商铺'],
        },
        {
            id: 1153104,
            villageName: '云通嘉园',
            villageId: 150775,
            name: '云通嘉园',
            developer: '云南云通房地产开发经营有限公司',
            city: '昆明市',
            district: '盘龙区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608322,5790',
            updateTime: '2019-08-08 11:45',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['商铺'],
        },
        {
            id: 1153103,
            villageName: '世博生态城低碳中心',
            villageId: 150825,
            name: '世博生态城低碳中心',
            developer: '云南世博兴云房地产有限公司',
            city: '昆明市',
            district: '盘龙区',
            newhouseType: '全网',
            source: '贝壳',
            sourceValue: 20,
            creatorName: null,
            phone: '4000608403,7938',
            updateTime: '2019-08-08 11:45',
            firstLiveTime: null,
            sellStatus: '售罄',
            onlineStatus: 0,
            operationStatus: 0,
            aroundCityVOList: null,
            propertyTypeNameList: ['住宅'],
        },
    ],
};
